const state={graph:null,content:null,nodes:[],links:[],typeMap:new Map(),enabledTypes:new Set(),selectedNode:null,hoveredNode:null,search:"",transform:{x:0,y:0,k:1},draggingNode:null,draggingView:false,lastPointer:null,scenario:"normal",costView:"loaded_cost",region:"JP",tone:"executive",severity:"moderate"};
const canvas=document.getElementById("graphCanvas");const ctx=canvas.getContext("2d");
const yen=new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0});
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
async function boot(){const [graph,content]=await Promise.all([fetch("./graph.json").then(r=>r.json()),fetch("./content.json").then(r=>r.json())]);state.graph=graph;state.content=content;state.typeMap=new Map(graph.types.map(t=>[t.id,t]));state.enabledTypes=new Set(graph.meta.initial_visible_types||graph.types.filter(t=>t.defaultVisible).map(t=>t.id));prepareGraph();renderStatic();renderControls();renderFilters();renderDetail(state.nodes[0]);bindTabs();bindGraphControls();resizeCanvas();requestAnimationFrame(tick)}
function prepareGraph(){const rings={center:0,control:130,process:260,role:390,cost_model:500,ledger:610,evidence:610,rule:600,template:620,index:640,incident:230,breach:190,affected_asset:310,posture_drop:340,remediation:360,loss:380};const byType=new Map();state.graph.nodes.forEach(n=>{if(!byType.has(n.type))byType.set(n.type,[]);byType.get(n.type).push(n)});state.nodes=state.graph.nodes.map(n=>{const group=byType.get(n.type)||[];const i=group.indexOf(n);const count=Math.max(1,group.length);const angle=(Math.PI*2*i/count)+typeOffset(n.type);const ring=rings[n.type]??560;return {...n,x:n.type==="center"?0:Math.cos(angle)*ring,y:n.type==="center"?0:Math.sin(angle)*ring,vx:0,vy:0,r:n.radius||12,fixed:n.type==="center",weight:1}});const map=new Map(state.nodes.map(n=>[n.id,n]));state.links=state.graph.links.map(l=>({...l,sourceNode:map.get(l.source),targetNode:map.get(l.target)})).filter(l=>l.sourceNode&&l.targetNode);state.links.forEach(l=>{l.sourceNode.weight+=.08;l.targetNode.weight+=.08})}
function typeOffset(type){return {control:.2,process:.7,role:1.1,cost_model:1.7,ledger:2.2,rule:2.8,template:3.4,index:4.0}[type]||0}
function renderStatic(){document.getElementById("heroEyebrow").textContent=state.content.hero.eyebrow;document.getElementById("heroTitle").textContent=state.content.hero.title;document.getElementById("heroLead").textContent=state.content.hero.lead;document.getElementById("overviewCards").innerHTML=state.content.overview_cards.map(c=>`<article class="overview-card"><h3>${e(c.title)}</h3><p>${e(c.body)}</p></article>`).join("");renderArticle();renderTypeSummary();renderChecklist()}
function renderArticle(){document.getElementById("articleBody").innerHTML=state.content.article.map((s,i)=>`<section class="article-section-card" id="${e(s.id)}"><div class="diagram-frame"><img src="${e(s.image)}" alt="${e(s.heading)} の図解" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><div class="diagram-placeholder" hidden>図解準備中</div></div><header><span class="section-number">${String(i+1).padStart(2,"0")}</span><div><h3>${e(s.heading)}</h3><p>${e(s.summary)}</p></div></header><ul class="section-points">${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul></section>`).join("")}
function renderTypeSummary(){document.getElementById("typeSummary").innerHTML=state.graph.types.map(t=>`<span class="type-chip" style="color:${t.color}"><span class="chip-dot"></span>${e(t.label)} ${state.graph.meta.counts[t.id]||0}</span>`).join("")}
function renderChecklist(){document.getElementById("checklistItems").innerHTML=state.content.checklist.map(i=>`<article class="check-item"><h3>${e(i.title)}</h3><p>${e(i.body)}</p></article>`).join("")}
function renderControls(){fillSelect("scenarioView",state.graph.views.scenario_view,state.scenario);fillSelect("costView",state.graph.views.cost_view,state.costView);fillSelect("regionView",state.graph.views.regions,state.region);fillSelect("toneView",state.graph.views.message_tone,state.tone);fillSelect("severityView",state.graph.views.breach_severity,state.severity)}
function fillSelect(id,items,value){const sel=document.getElementById(id);sel.innerHTML=items.map(x=>`<option value="${e(x.id)}" ${x.id===value?"selected":""}>${e(x.label)}</option>`).join("")}
function renderFilters(){const panel=document.getElementById("filterPanel");panel.innerHTML=state.graph.types.map(t=>`<button class="filter-chip ${state.enabledTypes.has(t.id)?"is-on":""}" data-type="${e(t.id)}" style="--type-color:${t.color}"><span class="chip-dot"></span>${e(t.label)} <span>${state.graph.meta.counts[t.id]||0}</span></button>`).join("");panel.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{const type=b.dataset.type;if(state.enabledTypes.has(type)){state.enabledTypes.delete(type);b.classList.remove("is-on")}else{state.enabledTypes.add(type);b.classList.add("is-on")}requestDraw()}))}
function bindTabs(){document.querySelectorAll("[data-tab], [data-tab-jump]").forEach(b=>b.addEventListener("click",ev=>{ev.preventDefault();setActiveTab(b.dataset.tab||b.dataset.tabJump)}))}
function setActiveTab(tab){document.querySelectorAll(".tab-button").forEach(b=>b.classList.toggle("is-active",b.dataset.tab===tab));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("is-active",p.id===tab));if(tab==="graph")setTimeout(resizeCanvas,40);window.scrollTo({top:0,behavior:"smooth"})}
function bindGraphControls(){document.getElementById("searchInput").addEventListener("input",ev=>{state.search=ev.target.value.trim().toLowerCase();requestDraw()});document.getElementById("resetView").addEventListener("click",()=>{state.transform={x:canvas.clientWidth/2,y:canvas.clientHeight/2,k:1};state.search="";document.getElementById("searchInput").value="";state.enabledTypes=new Set(state.graph.meta.initial_visible_types);renderFilters();renderDetail(state.nodes[0]);requestDraw()});["scenarioView","costView","regionView","toneView","severityView"].forEach(id=>document.getElementById(id).addEventListener("change",ev=>{const key={scenarioView:"scenario",costView:"costView",regionView:"region",toneView:"tone",severityView:"severity"}[id];state[key]=ev.target.value;document.getElementById("severityWrap").classList.toggle("is-hidden",state.scenario!=="breach");if(state.scenario==="breach"){["incident","breach","affected_asset","posture_drop","remediation","loss"].forEach(t=>state.enabledTypes.add(t));renderFilters()}renderDetail(state.selectedNode||state.nodes[0]);requestDraw()}));canvas.addEventListener("pointerdown",onPointerDown);canvas.addEventListener("pointermove",onPointerMove);canvas.addEventListener("pointerup",onPointerUp);canvas.addEventListener("pointerleave",onPointerUp);canvas.addEventListener("wheel",onWheel,{passive:false});window.addEventListener("resize",resizeCanvas)}
function resizeCanvas(){const rect=canvas.parentElement.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr);canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);if(!state.transform.x||!state.transform.y){state.transform.x=rect.width/2;state.transform.y=rect.height/2}requestDraw()}
function tick(){simulate();draw();requestAnimationFrame(tick)}
function simulate(){const visible=state.nodes.filter(isNodeVisible);const visibleLinks=state.links.filter(l=>isNodeVisible(l.sourceNode)&&isNodeVisible(l.targetNode));for(const l of visibleLinks){const dx=l.targetNode.x-l.sourceNode.x,dy=l.targetNode.y-l.sourceNode.y,d=Math.max(1,Math.hypot(dx,dy));const target=(l.sourceNode.type==="center"||l.targetNode.type==="center")?170:120;const f=(d-target)*.0025*(l.strength||1);const fx=dx/d*f,fy=dy/d*f;if(!l.sourceNode.fixed){l.sourceNode.vx+=fx;l.sourceNode.vy+=fy}if(!l.targetNode.fixed){l.targetNode.vx-=fx;l.targetNode.vy-=fy}}for(let i=0;i<visible.length;i++){for(let j=i+1;j<visible.length;j++){const a=visible[i],b=visible[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.max(10,Math.hypot(dx,dy));const f=520/(d*d),fx=dx/d*f,fy=dy/d*f;if(!a.fixed){a.vx-=fx;a.vy-=fy}if(!b.fixed){b.vx+=fx;b.vy+=fy}}}for(const n of visible){if(n.fixed||state.draggingNode===n){n.vx*=.2;n.vy*=.2;continue}n.vx+=-n.x*.0004;n.vy+=-n.y*.0004;n.vx*=.88;n.vy*=.88;n.x+=n.vx;n.y+=n.vy}}
function draw(){const rect=canvas.getBoundingClientRect();ctx.clearRect(0,0,rect.width,rect.height);ctx.save();ctx.translate(state.transform.x,state.transform.y);ctx.scale(state.transform.k,state.transform.k);const links=state.links.filter(l=>isNodeVisible(l.sourceNode)&&isNodeVisible(l.targetNode));drawLinks(links);drawNodes(state.nodes.filter(isNodeVisible));ctx.restore()}
function drawLinks(links){for(const l of links){const active=state.selectedNode&&(l.sourceNode===state.selectedNode||l.targetNode===state.selectedNode);const breach=state.scenario==="breach"&&l.scenario==="breach";const search=isSearchNeighbor(l.sourceNode)&&isSearchNeighbor(l.targetNode);ctx.strokeStyle=breach?"rgba(204,0,0,.55)":active||search?"rgba(39,125,161,.62)":"rgba(31,41,55,.13)";ctx.lineWidth=breach?2.6:active||search?2.1:1;ctx.beginPath();ctx.moveTo(l.sourceNode.x,l.sourceNode.y);ctx.lineTo(l.targetNode.x,l.targetNode.y);ctx.stroke();if(active){drawLinkLabel(l.label,(l.sourceNode.x+l.targetNode.x)/2,(l.sourceNode.y+l.targetNode.y)/2)}}}
function drawLinkLabel(label,x,y){ctx.save();ctx.font="11px sans-serif";const w=ctx.measureText(label).width+12;ctx.fillStyle="rgba(255,255,255,.94)";roundRect(ctx,x-w/2,y-11,w,22,6);ctx.fill();ctx.fillStyle="#277da1";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(label,x,y);ctx.restore()}
function drawNodes(nodes){for(const n of nodes){const type=state.typeMap.get(n.type)||{};const selected=n===state.selectedNode,matched=matchesSearch(n),neighbor=isSearchNeighbor(n);const dim=state.search&&!matched&&!neighbor;const color=type.color||"#277da1";const r=(n.r+(n.weight||1)*.7)*(selected?1.22:n===state.hoveredNode?1.1:1);ctx.save();ctx.globalAlpha=dim?.28:1;ctx.shadowColor=selected?"rgba(39,125,161,.32)":"rgba(0,0,0,.14)";ctx.shadowBlur=selected?18:7;ctx.fillStyle=color;ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=matched?4:neighbor?3:selected?3:2;ctx.strokeStyle=matched?"#f5a623":neighbor?"#111827":"#fff";ctx.stroke();if(n.type==="center"){ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(n.x,n.y,r*.36,0,Math.PI*2);ctx.fill()}drawNodeLabel(n,r);ctx.restore()}}
function drawNodeLabel(n,r){ctx.font=n.type==="center"?"700 13px sans-serif":"600 11px sans-serif";ctx.textAlign="center";ctx.textBaseline="top";const lines=wrapText(n.label,n.type==="center"?180:118);const lh=14,w=Math.min(n.type==="center"?190:130,Math.max(...lines.map(x=>ctx.measureText(x).width))+14),h=lines.length*lh+7,x=n.x-w/2,y=n.y+r+7;ctx.fillStyle="rgba(255,255,255,.9)";roundRect(ctx,x,y,w,h,6);ctx.fill();ctx.fillStyle="#1f2937";lines.forEach((line,i)=>ctx.fillText(line,n.x,y+4+i*lh))}
function wrapText(text,max){const hasSpace=String(text).includes(" ");const chars=hasSpace?String(text).split(" "):[...String(text)];let lines=[],line="";for(const c of chars){const next=hasSpace?`${line}${line?" ":""}${c}`:line+c;if(ctx.measureText(next).width>max&&line){lines.push(line);line=c}else line=next}if(line)lines.push(line);return lines.slice(0,3)}
function renderDetail(node){if(!node)return;state.selectedNode=node;const type=state.typeMap.get(node.type)||{label:node.type,color:"#277da1"};const neighbors=state.links.filter(l=>l.sourceNode===node||l.targetNode===node).map(l=>({label:l.sourceNode===node?l.targetNode.label:l.sourceNode.label,relation:l.label})).slice(0,12);document.getElementById("nodeDetail").innerHTML=`<div class="detail-title"><div class="detail-meta"><span class="type-chip" style="color:${type.color}"><span class="chip-dot"></span>${e(type.label)}</span>${(node.tags||[]).slice(0,4).map(t=>`<span class="type-chip">${e(t)}</span>`).join("")}</div><h3>${e(node.label)}</h3><p>${e(toneSummary(node))}</p></div>${metricsFor(node)}<div class="detail-section"><h4>表示条件</h4><p>${e(viewText())}</p></div><div class="detail-section"><h4>接続</h4><ul>${neighbors.map(n=>`<li>${e(n.relation)}: ${e(n.label)}</li>`).join("")}</ul></div>${node.path?`<div class="detail-section"><h4>Vault文書</h4><p>${e(node.path)}</p></div>`:""}`;requestDraw()}
function toneSummary(node){const base=node.summary||"詳細情報を表示します。";const prefix={technical:"技術観点: ",executive:"経営観点: ",audit:"監査観点: ",sales:"提案観点: "}[state.tone]||"";if(node.type==="process"&&state.scenario==="breach")return prefix+base+" 侵害発生時は追加工数と封じ込め・証跡化の負荷を加味します。";if(node.type==="role")return prefix+base+" スキル、資格、年収レンジ、AI補助可能性を合わせて確認します。";if(node.type==="control")return prefix+base+" 必要プロセスと証跡に接続して、実装と監査の説明に使います。";return prefix+base}
function metricsFor(node){if(!["process","role","control","cost_model"].includes(node.type))return"";const m=computeMetrics(node);return `<div class="detail-section"><h4>コスト表示</h4><div class="metric-grid">${m.map(x=>`<div class="metric"><span>${e(x.label)}</span><b>${e(x.value)}</b></div>`).join("")}</div></div>`}
function computeMetrics(node){if(node.type==="process"){const h=Number(node.annual_human_hours||0);const breach=node.scenario_effort?.breach?.[state.severity];const bh=state.scenario==="breach"&&breach?h+breach.additional_hours:h;const ai=Math.max(0,Math.round(bh*.68));const cost=Math.round(bh*9000*1.35);if(state.costView==="person_month")return[{label:"年間工数",value:`${Math.round(bh)}h`},{label:"AI補助後",value:`${ai}h`}];if(state.costView==="outsource")return[{label:"外注換算",value:yen.format(cost*1.5)},{label:"追加影響",value:state.scenario==="breach"?`${breach.additional_hours}h`:"なし"}];if(state.costView==="avoided_loss")return[{label:"影響カテゴリ",value:state.scenario==="breach"?"High":"Medium"},{label:"断定額",value:"表示しない"}];return[{label:"loaded cost",value:yen.format(cost)},{label:"削減目安",value:yen.format(Math.max(0,cost-Math.round(ai*9000*1.35)))}]}if(node.type==="role"){const band=node.salary_bands?.[state.region]?.mid||node.salary_bands?.JP?.mid;const med=band?.median||0;return[{label:"Mid中央値",value:med?yen.format(med):"未設定"},{label:"AI補助率",value:node.ai_assistability!=null?`${Math.round(node.ai_assistability*100)}%`:"未設定"}]}if(node.type==="control")return[{label:"実装状態",value:node.status||"active"},{label:"影響",value:state.scenario==="breach"?"High以上を確認":"通常確認"}];return[{label:"表示モード",value:state.costView},{label:"地域",value:state.region}]}
function viewText(){return `Scenario View: ${state.scenario} / Cost View: ${state.costView} / Region: ${state.region} / Message Tone: ${state.tone}${state.scenario==="breach"?` / Breach Severity: ${state.severity}`:""}`}
function isNodeVisible(n){if(!state.enabledTypes.has(n.type))return false;if(!state.search)return true;return matchesSearch(n)||isSearchNeighbor(n)}
function matchesSearch(n){if(!state.search)return false;return [n.label,n.summary,...(n.tags||[])].join(" ").toLowerCase().includes(state.search)}
function isSearchNeighbor(n){if(!state.search)return false;if(matchesSearch(n))return true;return state.links.some(l=>(l.sourceNode===n&&matchesSearch(l.targetNode))||(l.targetNode===n&&matchesSearch(l.sourceNode)))}
function onPointerDown(ev){canvas.setPointerCapture(ev.pointerId);const p=toGraphPoint(ev),n=findNode(p);state.lastPointer={x:ev.clientX,y:ev.clientY};if(n){state.draggingNode=n;renderDetail(n)}else state.draggingView=true}
function onPointerMove(ev){const p=toGraphPoint(ev);state.hoveredNode=findNode(p);canvas.style.cursor=state.hoveredNode?"grab":state.draggingView?"grabbing":"default";if(state.draggingNode){state.draggingNode.x=p.x;state.draggingNode.y=p.y;state.draggingNode.vx=0;state.draggingNode.vy=0}else if(state.draggingView&&state.lastPointer){state.transform.x+=ev.clientX-state.lastPointer.x;state.transform.y+=ev.clientY-state.lastPointer.y;state.lastPointer={x:ev.clientX,y:ev.clientY}}requestDraw()}
function onPointerUp(){state.draggingNode=null;state.draggingView=false;state.lastPointer=null}
function onWheel(ev){ev.preventDefault();const rect=canvas.getBoundingClientRect(),mx=ev.clientX-rect.left,my=ev.clientY-rect.top,old=state.transform.k,next=clamp(old*(ev.deltaY>0?.9:1.1),.42,2.6),gx=(mx-state.transform.x)/old,gy=(my-state.transform.y)/old;state.transform.k=next;state.transform.x=mx-gx*next;state.transform.y=my-gy*next;requestDraw()}
function toGraphPoint(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left-state.transform.x)/state.transform.k,y:(ev.clientY-r.top-state.transform.y)/state.transform.k}}
function findNode(p){return state.nodes.filter(isNodeVisible).slice().reverse().find(n=>Math.hypot(p.x-n.x,p.y-n.y)<=n.r+12)}
function requestDraw(){draw()}function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}function e(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
boot().catch(err=>{document.body.innerHTML=`<main class="container" style="padding:48px 0"><h1>読み込みに失敗しました</h1><p>${e(err.message)}</p></main>`});
